import assert from "node:assert/strict";
import test from "node:test";

import type { BootedRuntime } from "../src/boot.ts";
import type { ToolResult } from "../src/facade-launcher.ts";
import { BudgetExceeded, TurnCancelled, TurnContext, TurnDeadlineExceeded, defaultTurnLimits, type SessionContext } from "../src/runtime.ts";
import { cancelTurn, requiresClarification, resumeTurn, runTurn } from "../src/turn-runner.ts";

const context: SessionContext = { principal: "principal", capability_scope_id: "scope", allowed_access_classes: ["open"], allowed_capability_ids: ["capability"], allowed_refresh_profiles: ["profile"] };

test("(a) 9th facade call is rejected", async () => { const runtime = fake(async (driver) => { for (let index = 0; index < 9; index += 1) await driver.call("describe_market_data", {}); }); await run(runtime); assert.equal(runtime.results.at(-1)?.error?.code, "BUDGET_EXCEEDED"); });
test("(b) 4th status poll is rejected", async () => { const runtime = fake(async (driver) => { for (let index = 0; index < 4; index += 1) await driver.call("get_refresh_status", { job_ref: `${index}` }); }); await run(runtime); assert.equal(runtime.results.at(-1)?.error?.code, "BUDGET_EXCEEDED"); });
test("(c) 3rd finalization is rejected", async () => { const runtime = fake(async (driver) => { for (let index = 0; index < 3; index += 1) await driver.call("finalize_market_brief", {}); }); await run(runtime); assert.equal(runtime.results.at(-1)?.error?.code, "BUDGET_EXCEEDED"); });
test("(d) 21st query item is rejected", async () => { const runtime = fake(async (driver) => { await driver.call("query_market_data", { limit: 21 }); }); await run(runtime); assert.equal(runtime.results[0]?.error?.code, "BUDGET_EXCEEDED"); });
test("(e) 41st cumulative record is rejected", async () => { const runtime = fake(async (driver) => { await driver.call("query_market_data", { limit: 20 }); await driver.call("query_market_data", { limit: 20 }); await driver.call("describe_market_data", {}); }, [ok({ records: records(20) }), ok({ records: records(20) }), ok({ records: records(1) })]); await run(runtime); assert.equal(runtime.results.at(-1)?.error?.code, "BUDGET_EXCEEDED"); });
test("(f) 128 KiB plus one model bytes is rejected", async () => { const runtime = fake(async (driver) => { await driver.call("describe_market_data", {}); }, [ok({ blob: "x".repeat(defaultTurnLimits.cumulativeModelToolBytes) })]); await run(runtime); assert.equal(runtime.results[0]?.error?.code, "BUDGET_EXCEEDED"); });
test("(g) polling respects poll_after_seconds", async () => { const runtime = fake(async (driver) => { await driver.call("request_data_refresh", {}); await driver.call("get_refresh_status", { job_ref: "job" }); runtime.advance(15_000); await driver.call("get_refresh_status", { job_ref: "job" }); }, [ok({ job_ref: "job", poll_after_seconds: 15 }), ok({ job_ref: "job", job_state: "running" })]); await run(runtime); assert.equal(runtime.results[1]?.error?.code, "POLICY_DENIED"); assert.equal(runtime.results[2]?.status, "ok"); });
test("(h) deadline is surfaced as a typed error", async () => { const runtime = fake(async (driver) => { runtime.advance(45_000); await driver.call("describe_market_data", {}); }); await run(runtime); assert.equal(runtime.results[0]?.error?.code, "TURN_DEADLINE_EXCEEDED"); });
test("(i) terminal refresh requires re-query before finalization", async () => { const runtime = fake(async (driver) => { await driver.call("get_refresh_status", { job_ref: "job" }); await driver.call("finalize_market_brief", {}); await driver.call("query_market_data", { limit: 1 }); await driver.call("finalize_market_brief", {}); }, [ok({ job_ref: "job", job_state: "succeeded", canonical_changed: true }), ok({ records: [] })]); await run(runtime); assert.equal(runtime.results[1]?.error?.code, "REQUERY_REQUIRED"); assert.equal(runtime.results[3]?.status, "ok"); });
test("(j) cancel retains durable refresh and produces cancelled", async () => { const runtime = fake(async (driver) => { await driver.call("request_data_refresh", {}); cancelTurn(runtime.booted); }); const outcome = await run(runtime); assert.equal(outcome.terminal_state, "cancelled"); assert.equal(outcome.artifact, undefined); assert.equal(runtime.calls[0], "request_data_refresh"); });
test("(k) an ambiguous request clarifies with zero calls", async () => { const runtime = fake(async () => { throw new Error("must not prompt"); }); const outcome = await runTurn(runtime.booted, "what is the bank rate", { now: runtime.now }); assert.equal(outcome.clarification_requested, true); assert.equal(runtime.calls.length, 0); });
test("(l) latest has a time anchor and prompts Pi", async () => { const runtime = fake(async () => undefined); await run(runtime); assert.equal(runtime.prompts, 1); assert.equal(requiresClarification("latest bank rate"), false); });
test("(m) continuation reuses its original context and deadline", async () => { const runtime = fake(async () => undefined); const outcome = await run(runtime); const turn = outcome.turn; runtime.advance(1_000); const remaining = turn.getDeadlineRemainingMs(); const resumed = await resumeTurn(runtime.booted, outcome); assert.equal(resumed.turn, turn); assert.equal(turn.getDeadlineRemainingMs(), remaining); });
test("(n) split numeric model text fails without an artifact", async () => { const runtime = fake(async (_driver, emit) => { emit(delta("4")); emit(delta(".5")); emit(delta("%")); }); const outcome = await run(runtime); assert.equal(outcome.terminal_state, "failed"); assert.equal(outcome.artifact, undefined); });

type Driver = { readonly call: (toolName: string, args: unknown) => Promise<void> };
type Policy = { readonly preToolCall?: (toolName: string, args: unknown, turn: TurnContext) => ToolResult | undefined; readonly onResult?: (toolName: string, result: ToolResult, turn: TurnContext) => void };
function fake(script: (driver: Driver, emit: (event: Readonly<Record<string, unknown>>) => void) => Promise<void>, responses: readonly ToolResult[] = []) {
  let time = 0; let active: TurnContext | undefined; let policies: Policy = {}; let prompts = 0; const calls: string[] = []; const results: ToolResult[] = []; const queue = [...responses]; const listeners = new Set<(event: Readonly<Record<string, unknown>>) => void>();
  const driver: Driver = { async call(toolName, args) { const turn = active; assert.ok(turn); const blocked = policies.preToolCall?.(toolName, args, turn); if (blocked !== undefined) { results.push(blocked); return; } try { turn.beforeToolCall(toolName, itemArgs(args)); const response = queue.shift() ?? ok({}); calls.push(toolName); policies.onResult?.(toolName, response, turn); results.push(response); } catch (error) { results.push(errorResult(error)); } } };
  const session = { subscribe(listener: (event: Readonly<Record<string, unknown>>) => void) { listeners.add(listener); return () => listeners.delete(listener); }, async prompt() { prompts += 1; await script(driver, (event) => { for (const listener of listeners) listener(event); }); }, async abort() {} };
  const tools = ["describe_market_data", "query_market_data", "get_refresh_status", "request_data_refresh", "finalize_market_brief"].map((name) => ({ name }));
  const booted: BootedRuntime = { session, tools: tools as BootedRuntime["tools"], ctx: context, launcher: {} as BootedRuntime["launcher"], async finalizeBrief() { return {}; }, getTurnContext: () => active, setTurnContext: (turn) => { active = turn; }, setTurnPolicies: (next) => { policies = next; } };
  return { booted, now: () => time, advance: (milliseconds: number) => { time += milliseconds; }, calls, results, get prompts() { return prompts; } };
}
async function run(runtime: ReturnType<typeof fake>) { return runTurn(runtime.booted, "latest market data", { now: runtime.now }); }
function records(count: number): readonly Readonly<Record<string, unknown>>[] { return Array.from({ length: count }, () => ({ citation_refs: ["ref"] })); }
function ok(data: Readonly<Record<string, unknown>>): ToolResult { return { schema_version: "agent_tool_result.v1", request_id: null, status: "ok", data, warnings: [], error: null }; }
function delta(chunk: string): Readonly<Record<string, unknown>> { return { type: "message_update", assistantMessageEvent: { type: "text_delta", delta: chunk } }; }
function itemArgs(args: unknown): { readonly items?: number } { if (typeof args !== "object" || args === null || Array.isArray(args)) return {}; const record = args as Readonly<Record<string, unknown>>; return typeof record["limit"] === "number" ? { items: record["limit"] } : {}; }
function errorResult(error: unknown): ToolResult { const code = error instanceof BudgetExceeded ? "BUDGET_EXCEEDED" : error instanceof TurnDeadlineExceeded ? "TURN_DEADLINE_EXCEEDED" : error instanceof TurnCancelled ? "TURN_CANCELLED" : "INTERNAL_ERROR"; return { schema_version: "agent_tool_result.v1", request_id: null, status: "error", data: null, warnings: [], error: { code, message: code, retryable: false } }; }
